### ISSUE TITLE
匹配容易出现误匹配敏感词

### ISSUE THREAD

**Issue by lynchxiao** [qiyer/DFA_Cplusplus#1]
比如我的敏感词库里面有“手机魔卡”这个敏感词，则在发送“手机”这个词的时会判断为敏感词，实则“手机”这个不属于敏感词。

**Comment by qiyer** [comment]
我记得有这个问题开发时候一开始有，后来修复了，我试一下。。

**Comment by lynchxiao** [comment]
我昨天试了一次，把敏感词源数据删掉部分之后，就没有这个问题了。应该是敏感词源数据问题。谢谢你的回复！
